name: Update README Daily at 7 AM UTC+7/WIB

on:
  schedule:
    # Runs every day at 00:00 UTC (which is 7:00 AM UTC+7/WIB)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository code
      - uses: actions/checkout@v4

      # Update the content between the markers with WIB time
      - name: Update README content with WIB time
        run: |
          # Set the timezone to Asia/Jakarta (WIB) and format the date
          # Format example: Friday, 18 April 2025 07:00:00 WIB
          current_date_wib=$(TZ='Asia/Jakarta' date '+%A, %d %B %Y %H:%M:%S %Z')

          # Use sed to replace the content between the markers in README.md [1]
          # First, delete the old content between the markers
          sed -i '/<!-- LAST_UPDATED_START -->/,/<!-- LAST_UPDATED_END -->/{//!d}' README.md
          # Then, insert the new timestamp after the start marker
          sed -i "/<!-- LAST_UPDATED_START -->/a *Last updated: ${current_date_wib}*" README.md

      # Uses an action to automatically commit and push the changes
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: Update README with last updated timestamp (WIB)'
          file_pattern: README.md # Only commit if README.md changed
          commit_options: '--no-verify' # Optional: Skip pre-commit hooks if any
